# -*- coding: utf-8 -*-
"""MYC_Docking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-KWXehftshvs-PxKH6U2TFFzaTLMI5G
"""

!pip install biopython requests pandas matplotlib py3Dmol -q
!apt-get update -y
!apt-get install openbabel -y -qq

!wget https://github.com/gnina/gnina/releases/download/v1.1/gnina -O gnina
!chmod +x gnina
!./gnina --help

from Bio import Entrez, SeqIO
from Bio.Blast import NCBIWWW, NCBIXML
from Bio.PDB import PDBParser, PDBIO, Select, Superimposer
from IPython.display import display, HTML

import pandas as pd
import numpy as np
import requests
import py3Dmol
import matplotlib.pyplot as plt
import os

Entrez.email = "subhanajamil3@gmail.com"

gene = "MYC"
ncbi_mrna_id = "NM_002467.6"
protein_ref_id = "NP_002458.2"

print("Gene selected:", gene)
print("mRNA ID:", ncbi_mrna_id)
print("Protein Ref:", protein_ref_id)

handle = Entrez.efetch(
    db="nucleotide",
    id="NM_002467.6",
    rettype="gb",
    retmode="text"
)

record = SeqIO.read(handle, "genbank")
handle.close()

print("Sequence ID:", record.id)
print("Sequence Length:", len(record.seq))

cds_seq = None

for feature in record.features:
    if feature.type == "CDS":
        cds_seq = feature.extract(record.seq)
        break

if cds_seq is None:
    raise ValueError("Coding region not found")

print("CDS length:", len(cds_seq))

mrna = cds_seq.transcribe()

print("mRNA length:", len(mrna))
print(mrna[:100])

blast_result = NCBIWWW.qblast(
    "blastn",
    "nt",
    str(mrna),
    hitlist_size=5
)

with open("MYC_blast.xml", "w") as f:
    f.write(blast_result.read())

protein = mrna.translate(to_stop=True)

print("Protein length:", len(protein))
print(protein[:100])

handle = Entrez.efetch(
    db="protein",
    id="NP_002458.2",
    rettype="fasta",
    retmode="text"
)

ref_protein = SeqIO.read(handle, "fasta").seq
handle.close()

print("Reference protein loaded")

url = "https://alphafold.ebi.ac.uk/files/AF-P01106-F1-model_v6.pdb"
r = requests.get(url)

with open("MYC_alphafold.pdb", "w") as f:
    f.write(r.text)

view = py3Dmol.view(width=800, height=400)

with open("MYC_alphafold.pdb") as f:
    view.addModel(f.read(), "pdb")

view.setStyle({"cartoon": {"color": "spectrum"}})
view.zoomTo()
view.show()

import requests

cid = "9835049"
url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{cid}/SDF"

r = requests.get(url)

print("Status:", r.status_code)
print(r.text[:200])

if "V2000" in r.text or "M  END" in r.text:
    with open("MYC_ligand.sdf", "w") as f:
        f.write(r.text)
    print("Ligand saved correctly")
else:
    raise ValueError("Invalid ligand file downloaded")

from Bio.PDB import PDBParser

parser = PDBParser(QUIET=True)
structure = parser.get_structure("MYC", "MYC_alphafold.pdb")

coords = [atom.coord for atom in structure.get_atoms()]
coords = np.array(coords)

print("Atoms:", len(coords))

if len(coords) == 0:
    raise ValueError("Empty protein structure")

center = coords.mean(axis=0)

print("Docking center:", center)

gnina_command = f"""./gnina \
-r MYC_alphafold.pdb \
-l MYC_ligand.pdbqt \
--center_x {center[0]:.3f} \
--center_y {center[1]:.3f} \
--center_z {center[2]:.3f} \
--size_x 40 \
--size_y 40 \
--size_z 40 \
--num_modes 10 \
-o MYC_docked.sdf
"""

!{gnina_command}

import matplotlib.pyplot as plt

modes = list(range(1, 11))

scores = [
    -4.03, -3.82, -3.58, -3.56, -4.05,
    -3.58, -3.60, -4.16, -4.93, -3.61
]

plt.bar(modes, scores)
plt.gca().invert_yaxis()
plt.title("MYC GNINA Docking Scores (Affinity)")
plt.xlabel("Docking Mode")
plt.ylabel("Affinity (kcal/mol)")
plt.show()

import py3Dmol

view = py3Dmol.view(width=800, height=400)

# Protein
view.addModel(open("MYC_alphafold.pdb").read(), "pdb")
view.setStyle({"cartoon": {"color": "blue"}})

# Docked ligand (GNINA output SDF)
view.addModel(open("MYC_docked.sdf").read(), "sdf")
view.setStyle({"stick": {"colorscheme": "greenCarbon"}})

view.zoomTo()
view.show()

from IPython.display import HTML
import py3Dmol

# Title
display(HTML("<h3>MYC–10058-F4 Docked Complex</h3>"))

# Protein
with open("MYC_alphafold.pdb") as f:
    protein = f.read()

# Docked ligand from GNINA output (SDF)
with open("MYC_docked.sdf") as f:
    ligand = f.read()

# Viewer
view = py3Dmol.view(width=850, height=500)

# Protein structure
view.addModel(protein, "pdb")
view.setStyle({"model": 0}, {"cartoon": {"color": "spectrum"}})

# Docked ligand
view.addModel(ligand, "sdf")
view.setStyle({"model": 1}, {"stick": {"colorscheme": "greenCarbon"}})

view.zoomTo()
view.show()